GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json


###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Poezie"
}

###
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Amintiri"
}

###
DELETE  http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json